project_id = "jufvrlenxbcmohpkuvlo"

[functions.price-check]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.optimize-listing]
verify_jwt = false

[functions.translate-listing]
verify_jwt = false

[functions.redeem-referral]
verify_jwt = false

[functions.vintography]
verify_jwt = false

[functions.import-wardrobe]
verify_jwt = false

[functions.scrape-vinted-url]
verify_jwt = false

[functions.buy-credits]
verify_jwt = false

[functions.generate-hashtags]
verify_jwt = false

[functions.photo-studio]
verify_jwt = false
